---
- hosts: all
  become: true
  gather_facts: yes
  tasks:

  - name: Install python3 and pip3
    package:
      name:
        - "{{ python_package }}"
        - "{{ pip_package }}"
      state: latest
  
  - name: Set pip3 as default pip in Ubuntu
    command: "ln -sf /usr/bin/pip3 /usr/bin/pip"
    when: ansible_distribution == 'Ubuntu'

  - name: Set pip3 as default pip in CentOS
    command: "ln -sf /usr/bin/pip3 /usr/bin/pip"
    when: ansible_distribution == 'CentOS'

  - name: Set pip3 as default python3 in Ubuntu
    command: "ln -sf /usr/bin/python3 /usr/bin/python"
    when: ansible_distribution == 'Ubuntu'

  - name: Set pip3 as default python3 in CentOS
    command: "ln -sf /usr/bin/python3 /usr/bin/python"
    when: ansible_distribution == 'CentOS'

  - name: Install Java OpenJDK in Ubuntu and CentOS
    package:
      name: openjdk-11-jdk
      state: latest

  - name: Create a MOTD File
    template: 
      src: /home/ralph/Diocera_PrelimExam/motd.j2
      dest: /etc/motd

  - name: Determine if the new user exists
    user: 
      name: "{{ new_user }}"
      state: present

